language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t shantanu616/devops_planet -f Dockerfile.dev .
script:
  - docker run -e CI=true shantanu616/devops_planet npm run test
