version: "3"
services:
  planetshare:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    volumes:
      - /var/planetshare/node_modules
      - .:/var/planetshare
